### ISSUE TITLE
getClientSecret retunr null with error

### ISSUE THREAD

**Issue by the-lensky** [headlesscommerce/vsf-magento-stripe#11]
Inside usePaymentIntent.ts file in function getClientSecret   `result = createPaymentIntentResponse?.data['createPaymentIntent']?.clientSecret; `return null
have error debugMessage: 
"Call to undefined method StripeIntegration\\Payments\\Api\\Service::get_client_secret()"

**Comment by davidwindell** [comment]
@the-lensky which version of the Magento module do you have installed?

**Comment by the-lensky** [comment]
@davidwindell version 3.4 was installed. Problem was that stripe remove method that used in this library. After downgrading to 3.3 everything was fixed.

I have several more questions, but i think I open a new issue for that..?
