### ISSUE TITLE
Add support for Stripe Magento module v3.4+

### ISSUE THREAD

**Issue by davidwindell** [headlesscommerce/vsf-magento-stripe#5]
Stripe's Magento 2 module v3.4.0 is currently in beta (predicted launch end of March 2023). It adds support for [Deferred Intent Creation](https://stripe.com/docs/payments/defer-intent-creation).

This will allow the rendering of the PaymentElement without creating a PaymentIntent. In turn that will mean we can remove our reliance on the custom extension to the Magento module as we would no longer need a client secret before showing the PaymentElement.

We may have to replace `vue-stripe` with the Stripe Javascript SDK directly to get immediate support for this feature.

The workflow we will need to replicate is demonstrated here:

https://github.com/snez/magento2-graphql-place-order/blob/payment_element/payment_element_order.html

Help wanted and welcome!

**Comment by tajdev1** [comment]
Hey @davidwindell,

Stripe Magento module v3.4 is out. Did you guys added support of it or is it still WIP?

Thanks

**Comment by davidwindell** [comment]
@tajdev1 this is still pending development to start, we welcome contributions in the meantime!

**Comment by bensinca** [comment]
WIP: https://github.com/headlesscommerce/vsf-magento-stripe/tree/migrate-to-stripe-magento-v-3-4
